/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) codegen_dynamics_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y

/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  #define fmin CASADI_PREFIX(fmin)
  casadi_real fmin(casadi_real x, casadi_real y) { return x<y ? x : y;}
  #define fmax CASADI_PREFIX(fmax)
  casadi_real fmax(casadi_real x, casadi_real y) { return x>y ? x : y;}
#endif

/* CasADi extensions */
#define sq CASADI_PREFIX(sq)
casadi_real sq(casadi_real x) { return x*x;}
#define sign CASADI_PREFIX(sign)
casadi_real CASADI_PREFIX(sign)(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define twice CASADI_PREFIX(twice)
casadi_real twice(casadi_real x) { return x+x;}
#define if_else CASADI_PREFIX(if_else)
casadi_real if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Printing routine */
#define PRINTF printf

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};

/* dynamics:(i0[13],i1[3])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[0] ? arg[0][2] : 0;
  casadi_real a1=arg[0] ? arg[0][0] : 0;
  casadi_real a2=1.0000000000000000e-04;
  casadi_real a3=(a1+a2);
  a3=atan2(a0,a3);
  casadi_real a4=2.;
  casadi_real a5=(a3/a4);
  a5=cos(a5);
  casadi_real a6=arg[0] ? arg[0][1] : 0;
  casadi_real a7=sq(a1);
  casadi_real a8=sq(a6);
  a7=(a7+a8);
  a8=sq(a0);
  a7=(a7+a8);
  a7=sqrt(a7);
  a7=(a7+a2);
  a2=(a6/a7);
  a2=asin(a2);
  a8=(a2/a4);
  a8=(-a8);
  a8=sin(a8);
  casadi_real a9=(a5*a8);
  casadi_real a10=(a2/a4);
  a10=cos(a10);
  a5=(a5*a10);
  casadi_real a11=sq(a5);
  a4=(a3/a4);
  a4=sin(a4);
  a8=(a4*a8);
  casadi_real a12=sq(a8);
  a11=(a11+a12);
  a10=(a10*a4);
  a4=sq(a10);
  a11=(a11+a4);
  a4=sq(a9);
  a11=(a11+a4);
  a11=sqrt(a11);
  a4=(a9/a11);
  a12=8.8999999999999996e-02;
  casadi_real a13=1.6000000000000000e-02;
  casadi_real a14=1.2780000000000000e-01;
  casadi_real a15=7.8845999999999998e+00;
  casadi_real a16=(a15*a3);
  a16=(a14+a16);
  a16=sq(a16);
  casadi_real a17=4.2180703719166232e+01;
  a16=(a16/a17);
  a13=(a13+a16);
  a16=-9.8229999999999998e-02;
  a17=arg[1] ? arg[1][0] : 0;
  a16=(a16*a17);
  a13=(a13+a16);
  a16=5.1250000000000000e+02;
  casadi_real a18=sq(a7);
  a16=(a16*a18);
  a13=(a13*a16);
  a13=(a12*a13);
  a18=(a4*a13);
  casadi_real a19=(a8/a11);
  a15=(a15*a3);
  a14=(a14+a15);
  a15=-3.2700000000000000e+00;
  a15=(a15*a17);
  a14=(a14+a15);
  a14=(a14*a16);
  a14=(a12*a14);
  a15=1.9557636524999998e+02;
  a15=(a15*a7);
  casadi_real a20=arg[0] ? arg[0][4] : 0;
  a15=(a15*a20);
  a14=(a14+a15);
  a15=(a19*a14);
  a18=(a18-a15);
  a15=(a18*a9);
  casadi_real a21=(a10/a11);
  casadi_real a22=(a21*a13);
  a11=(a5/a11);
  casadi_real a23=(a11*a14);
  a22=(a22+a23);
  a23=(a22*a10);
  a15=(a15+a23);
  a19=(a19*a13);
  a4=(a4*a14);
  a19=(a19+a4);
  a4=(a19*a8);
  a15=(a15-a4);
  a21=(a21*a14);
  a11=(a11*a13);
  a21=(a21-a11);
  a11=(a5*a21);
  a15=(a15+a11);
  a11=93.;
  a15=(a15+a11);
  a11=-10.;
  a11=(a11*a1);
  a15=(a15+a11);
  a11=4.7070999999999998e+01;
  a13=9.8100000000000005e+00;
  a14=arg[0] ? arg[0][10] : 0;
  a4=arg[0] ? arg[0][9] : 0;
  a23=sq(a4);
  casadi_real a24=sq(a14);
  a23=(a23+a24);
  a24=arg[0] ? arg[0][11] : 0;
  casadi_real a25=sq(a24);
  a23=(a23+a25);
  a25=arg[0] ? arg[0][12] : 0;
  casadi_real a26=sq(a25);
  a23=(a23+a26);
  a23=sqrt(a23);
  a26=(a14/a23);
  a26=(a13*a26);
  casadi_real a27=(a26*a25);
  casadi_real a28=(a4/a23);
  a28=(a13*a28);
  casadi_real a29=(a28*a24);
  a27=(a27-a29);
  a29=(a25/a23);
  a29=(a13*a29);
  casadi_real a30=(a29*a14);
  a27=(a27+a30);
  a23=(a24/a23);
  a13=(a13*a23);
  a23=(a4*a13);
  a27=(a27-a23);
  a27=(a11*a27);
  a15=(a15+a27);
  a15=(a15/a11);
  a27=(a20*a0);
  a23=arg[0] ? arg[0][5] : 0;
  a30=(a23*a6);
  a27=(a27-a30);
  a15=(a15-a27);
  if (res[0]!=0) res[0][0]=a15;
  a15=(a5*a18);
  a27=(a22*a8);
  a30=(a21*a9);
  a27=(a27+a30);
  a30=(a19*a10);
  a27=(a27+a30);
  a15=(a15-a27);
  a27=-7.3389000000000004e-01;
  a27=(a27*a2);
  a30=-1.1210000000000001e-01;
  casadi_real a31=arg[1] ? arg[1][2] : 0;
  a30=(a30*a31);
  a27=(a27+a30);
  a27=(a27*a16);
  a27=(a12*a27);
  a30=1.0034750000000000e+02;
  casadi_real a32=2.5000000000000000e-01;
  casadi_real a33=2.0261000000000000e+00;
  a33=(a33*a23);
  casadi_real a34=8.2799999999999996e-01;
  casadi_real a35=arg[0] ? arg[0][3] : 0;
  a34=(a34*a35);
  a33=(a33+a34);
  a32=(a32*a33);
  a30=(a30*a32);
  a30=(a30*a7);
  a27=(a27+a30);
  a15=(a15+a27);
  a27=-20.;
  a27=(a27*a6);
  a15=(a15+a27);
  a27=(a28*a14);
  a30=(a13*a25);
  a27=(a27+a30);
  a30=(a29*a24);
  a27=(a27+a30);
  a30=(a4*a26);
  a27=(a27+a30);
  a27=(a11*a27);
  a15=(a15+a27);
  a15=(a15/a11);
  a27=(a23*a1);
  a30=(a35*a0);
  a27=(a27-a30);
  a15=(a15-a27);
  if (res[0]!=0) res[0][1]=a15;
  a21=(a21*a10);
  a18=(a18*a8);
  a21=(a21-a18);
  a19=(a19*a9);
  a21=(a21-a19);
  a22=(a5*a22);
  a21=(a21-a22);
  a22=-5.;
  a22=(a22*a0);
  a21=(a21+a22);
  a29=(a29*a25);
  a13=(a13*a24);
  a26=(a26*a14);
  a13=(a13+a26);
  a29=(a29-a13);
  a28=(a4*a28);
  a29=(a29+a28);
  a29=(a11*a29);
  a21=(a21+a29);
  a21=(a21/a11);
  a11=(a35*a6);
  a29=(a20*a1);
  a11=(a11-a29);
  a21=(a21-a11);
  if (res[0]!=0) res[0][2]=a21;
  a21=1.3284395165607973e-01;
  a11=sq(a5);
  a29=sq(a8);
  a11=(a11+a29);
  a29=sq(a10);
  a11=(a11+a29);
  a29=sq(a9);
  a11=(a11+a29);
  a11=sqrt(a11);
  a29=(a8/a11);
  a28=1.1000000000000001e+00;
  a13=9.7897999999999996e-01;
  a13=(a13*a2);
  a26=1.1930000000000000e-01;
  a22=arg[1] ? arg[1][1] : 0;
  a26=(a26*a22);
  a13=(a13+a26);
  a26=-1.2396000000000001e+01;
  a26=(a26*a31);
  a13=(a13+a26);
  a13=(a13*a16);
  a13=(a12*a13);
  a13=(a28*a13);
  a26=2.7595562500000003e+01;
  a19=-1.1299999999999999e+00;
  a19=(a19*a35);
  a18=-2.7004000000000001e+00;
  a18=(a18*a23);
  a19=(a19+a18);
  a19=(a26*a19);
  a19=(a19*a7);
  a13=(a13+a19);
  a19=(a29*a13);
  a18=(a9/a11);
  a15=3.7912000000000001e-01;
  a15=(a15*a2);
  a2=1.4119999999999999e-01;
  a2=(a2*a22);
  a15=(a15+a2);
  a2=1.2350000000000000e-01;
  a2=(a2*a31);
  a15=(a15+a2);
  a15=(a15*a16);
  a15=(a12*a15);
  a28=(a28*a15);
  a15=-1.0024999999999999e+00;
  a15=(a15*a23);
  a2=-1.1719999999999999e+00;
  a2=(a2*a35);
  a15=(a15+a2);
  a26=(a26*a15);
  a26=(a26*a7);
  a28=(a28+a26);
  a26=(a18*a28);
  a19=(a19-a26);
  a26=(a5/a11);
  a15=8.3000000000000004e-02;
  a2=7.3800000000000004e-02;
  a31=-3.0968000000000000e+01;
  a31=(a31*a3);
  a2=(a2+a31);
  a31=1.7492000000000001e+01;
  a31=(a31*a17);
  a2=(a2+a31);
  a2=(a2*a16);
  a12=(a12*a2);
  a15=(a15*a12);
  a12=-3.4816075985000003e+02;
  a12=(a12*a20);
  a12=(a12*a7);
  a15=(a15+a12);
  a12=(a26*a15);
  a19=(a19+a12);
  a12=(a19*a9);
  a11=(a10/a11);
  a7=(a11*a28);
  a2=(a29*a15);
  a7=(a7-a2);
  a2=(a26*a13);
  a7=(a7+a2);
  a2=(a7*a10);
  a12=(a12-a2);
  a29=(a29*a28);
  a2=(a11*a15);
  a29=(a29+a2);
  a2=(a18*a13);
  a29=(a29+a2);
  a2=(a29*a8);
  a12=(a12+a2);
  a18=(a18*a15);
  a11=(a11*a13);
  a18=(a18-a11);
  a26=(a26*a28);
  a18=(a18+a26);
  a26=(a5*a18);
  a12=(a12+a26);
  a26=-2000.;
  a26=(a26*a35);
  a12=(a12+a26);
  a26=-1.3102595866413809e+00;
  a28=(a26*a35);
  a11=1.0535031757256275e+01;
  a11=(a11*a23);
  a28=(a28+a11);
  a11=(a20*a28);
  a13=1.7578055285911734e+01;
  a13=(a13*a20);
  a15=(a23*a13);
  a11=(a11-a15);
  a12=(a12-a11);
  a21=(a21*a12);
  a11=1.6522025295729575e-02;
  a15=(a18*a10);
  a2=(a19*a8);
  a15=(a15-a2);
  a2=(a29*a9);
  a15=(a15+a2);
  a2=(a5*a7);
  a15=(a15+a2);
  a2=-300.;
  a2=(a2*a23);
  a15=(a15+a2);
  a13=(a35*a13);
  a2=7.6905883128154029e+00;
  a2=(a2*a35);
  a26=(a26*a23);
  a2=(a2+a26);
  a26=(a20*a2);
  a13=(a13-a26);
  a15=(a15-a13);
  a13=(a11*a15);
  a21=(a21+a13);
  if (res[0]!=0) res[0][3]=a21;
  a21=5.6889114508672005e-02;
  a7=(a7*a8);
  a18=(a18*a9);
  a7=(a7-a18);
  a29=(a29*a10);
  a7=(a7+a29);
  a5=(a5*a19);
  a7=(a7+a5);
  a5=-800.;
  a5=(a5*a20);
  a7=(a7+a5);
  a2=(a23*a2);
  a28=(a35*a28);
  a2=(a2-a28);
  a7=(a7-a2);
  a21=(a21*a7);
  if (res[0]!=0) res[0][4]=a21;
  a11=(a11*a12);
  a12=9.6976275494449704e-02;
  a12=(a12*a15);
  a11=(a11+a12);
  if (res[0]!=0) res[0][5]=a11;
  a11=(a14*a6);
  a12=(a24*a1);
  a11=(a11-a12);
  a12=(a4*a0);
  a11=(a11+a12);
  a12=sq(a4);
  a15=sq(a14);
  a12=(a12+a15);
  a15=sq(a24);
  a12=(a12+a15);
  a15=sq(a25);
  a12=(a12+a15);
  a12=sqrt(a12);
  a15=(a24/a12);
  a21=(a11*a15);
  a7=(a25*a1);
  a2=(a14*a0);
  a7=(a7-a2);
  a2=(a4*a6);
  a7=(a7+a2);
  a2=(a25/a12);
  a28=(a7*a2);
  a21=(a21-a28);
  a28=(a14*a1);
  a5=(a24*a6);
  a28=(a28+a5);
  a5=(a25*a0);
  a28=(a28+a5);
  a5=(a14/a12);
  a19=(a28*a5);
  a21=(a21+a19);
  a12=(a4/a12);
  a0=(a24*a0);
  a6=(a25*a6);
  a0=(a0-a6);
  a1=(a4*a1);
  a0=(a0+a1);
  a1=(a12*a0);
  a21=(a21+a1);
  if (res[0]!=0) res[0][6]=a21;
  a21=(a0*a2);
  a1=(a11*a5);
  a21=(a21-a1);
  a1=(a28*a15);
  a21=(a21+a1);
  a1=(a12*a7);
  a21=(a21+a1);
  if (res[0]!=0) res[0][7]=a21;
  a7=(a7*a5);
  a0=(a0*a15);
  a7=(a7-a0);
  a28=(a28*a2);
  a7=(a7+a28);
  a12=(a12*a11);
  a7=(a7+a12);
  if (res[0]!=0) res[0][8]=a7;
  a7=5.0000000000000000e-01;
  a12=(a14*a35);
  a11=(a24*a20);
  a12=(a12+a11);
  a11=(a25*a23);
  a12=(a12+a11);
  a12=(a7*a12);
  a12=(-a12);
  if (res[0]!=0) res[0][9]=a12;
  a12=(a24*a23);
  a11=(a25*a20);
  a12=(a12-a11);
  a11=(a4*a35);
  a12=(a12+a11);
  a12=(a7*a12);
  if (res[0]!=0) res[0][10]=a12;
  a25=(a25*a35);
  a12=(a14*a23);
  a25=(a25-a12);
  a12=(a4*a20);
  a25=(a25+a12);
  a25=(a7*a25);
  if (res[0]!=0) res[0][11]=a25;
  a14=(a14*a20);
  a24=(a24*a35);
  a14=(a14-a24);
  a4=(a4*a23);
  a14=(a14+a4);
  a7=(a7*a14);
  if (res[0]!=0) res[0][12]=a7;
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void dynamics_incref(void) {
}

CASADI_SYMBOL_EXPORT void dynamics_decref(void) {
}

CASADI_SYMBOL_EXPORT int dynamics_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT int dynamics_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* dynamics_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dynamics_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* dynamics_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* dynamics_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dynamics_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 36;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
